[package]
name = "marinade_finance_interface"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = ">=0.9"
solana-program = "^1"
thiserror = "^1"
num-derive = ">=0.1"
num-traits = ">=0.1"

[dependencies.serde]
optional = true
version = "^1"
